routes/web.php
<?php

use App\Http\Controllers\Blog\BlogsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [BlogsController::class, 'index'])->name('home');
Route::get('/users/{user}', [UsersController::class, 'show'])->name('users.show');
Route::resource('blogs', BlogsController::class);

Auth::routes();
Auth::routes(['verify' => true]);
Route::get('/verify', [HomeController::class, 'confirmation'])->name('confirmation');

Route::get('/home', [HomeController::class, 'index'])->name('home');

app/Models/Blog.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Blog extends Model
{
    use HasFactory;
    protected $fillable = ['title', 'body', 'user_id'];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return string
     */
    public function getDateTime(): string
    {
        $date = Carbon::parse($this->created_at);
        return $date->format('d.m.Y H:i');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * @return HasMany
     */
    public function blogs(): HasMany
    {
        return $this->hasMany(Blog::class);
    }
}

app/Http/Controllers/Blog/BlogsController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Http\Controllers\Controller;
use App\Http\Requests\BlogCreateRequest;
use App\Http\Requests\BlogEditRequest;
use App\Models\Blog;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\View as ViewType;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;

class BlogsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * @return ViewType
     */
    public function index(): ViewType
    {
        $blogs = Blog::orderBy('created_at', 'desc')->paginate(12);
        return view('blog.index', compact('blogs'));
    }

    /**
     * @return ViewType
     */
    public function create(): ViewType
    {
        $user = Auth::user();
        return view('blog.create', compact('user'));
    }


    /**
     * @param BlogCreateRequest $request
     * @return RedirectResponse
     */
    public function store(BlogCreateRequest $request): RedirectResponse
    {
        $data = $request->validated();
        $blog = Blog::create($data);
        return redirect()->route('blogs.show', ['blog' => $blog])->with('status', __("Блог успешно был создан!"));
    }


    /**
     * @param Blog $blog
     * @return ViewType
     */
    public function show(Blog $blog): ViewType
    {
        return view('blog.show', compact('blog'));
    }


    /**
     * @param Blog $blog
     * @return ViewType
     * @throws AuthorizationException
     */
    public function edit(Blog $blog): ViewType
    {
        $this->authorize('deleteOrUpdate', $blog);
        return view('blog.edit', compact('blog'));
    }


    /**
     * @param BlogEditRequest $request
     * @param Blog $blog
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(BlogEditRequest $request, Blog $blog): RedirectResponse
    {
        $this->authorize('deleteOrUpdate', $blog);
        $data = $request->validated();
        $blog->update($data);
        return redirect()->route('blogs.show', ['blog' => $blog])->with('status', __("Блог успешно был обновлен!"));
    }


    /**
     * @param Blog $blog
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Blog $blog): RedirectResponse
    {
        $this->authorize('deleteOrUpdate', $blog);
        $blog->delete();
        return redirect()->route('blogs.index')->with('status', __("Блог успешно был удален!"));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Notifications\SuccessRegisterNotification;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Contracts\View\View as ViewType;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return Renderable
     */
    public function index(): Renderable
    {
        $user = Auth::user();
        $user->notify(new SuccessRegisterNotification($user));
        return view('home');
    }

    /**
     * @return ViewType
     */
    public function confirmation(): ViewType
    {
        return view('confirmation');
    }
}

app/Http/Controllers/User/UsersController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\View\View as ViewType;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->only('show');
    }

    /**
     * @param User $user
     * @return ViewType
     */
    public function show(User $user): ViewType
    {
        $blogs = $user->blogs()->paginate(6);
        return view('user.show', compact('user', 'blogs'));
    }
}

resources/views/blog/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-12">
            <form method="POST" action="{{route('blogs.store')}}">
                @csrf
                <input type="hidden" name="user_id" value="{{$user->id}}">
                <div class="mb-3">
                    <label for="title" class="form-label">{{__('Заголовок')}}</label>
                    <input type="text" name="title" class="form-control" id="title"
                           aria-describedby="title" value="{{ old('title') }}">
                    @error('title')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="content" class="form-label">{{__('Блог')}}</label>
                    <textarea type="text" name="body" class="form-control" id="content"
                              aria-describedby="content">{{old('body')}}</textarea>
                    @error('body')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">{{__('Добавить')}}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/blog/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-12">
            <form method="POST" action="{{route('blogs.update', ['blog' => $blog])}}">
                @method('PUT')
                @csrf
                <input type="hidden" name="user_id" value="{{$blog->user->id}}">
                <div class="mb-3">
                    <label for="title" class="form-label">{{__('Заголовок')}}</label>
                    <input type="text" name="title" class="form-control" id="title"
                           aria-describedby="title" VALUE="{{$blog->title}}">
                    @error('title')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="content" class="form-label">{{__('Блог')}}</label>
                    <textarea type="text" name="body" class="form-control" id="content"
                              aria-describedby="content">{{$blog->body}}</textarea>
                    @error('body')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">{{__('Сохранить')}}</button>
            </form>
        </div>
    </div>


@endsection

resources/views/blog/index.blade.php
@extends('layouts.app')
@section('content')
    @guest()
        <p class="registr">{{__('Войдите в систему для того что бы добавить пост!')}}</p>
    @endguest
    <a class="btn btn-success mb-2" href="{{route('blogs.create')}}">{{__('Добавить пост')}}</a>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach($blogs as $blog)
            <div class="col">
                <div class="card h-100">
                    <div class="card-footer">
                        <small class="text-muted">{{$blog->title}}</small>
                    </div>
                    <a href="{{route('blogs.show', ['blog' => $blog->id])}}" class="card-body text-decoration-none">
                        <h5 class="card-title">{{$blog->title}}</h5>
                        <p class="card-text">{{$blog->body}}</p>
                    </a>
                    <div class="card-footer d-flex flex-column">
                        <small class="text-muted">{{__('Дата:')}} {{$blog->getDateTime()}}</small>
                        <small class="text-muted">{{__('Автор:')}} <a
                                href="{{route('users.show', ['user' => $blog->user->id])}}">{{$blog->user->name}}</a></small>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="justify-content-center pb-3 mt-3">
        <ul class="pagination-list">
            {{ $blogs->links() }}
        </ul>
    </div>
@endsection

resources/views/blog/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            <a href="{{route('users.show', ['user' => $blog->user->id])}}">
                {{$blog->user->name}}
            </a>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{$blog->title}}</h5>
            <p class="card-text">{{$blog->body}}</p>
        </div>
        <div class="card-footer text-muted">
            Дата: {{$blog->getDateTime()}}
        </div>
    </div>
    @canany('deleteOrUpdate', $blog)
        <a href="{{route('blogs.edit', ['blog' => $blog->id])}}" class="btn btn-success btn-lg edit mt-2"
           type="button"> {{__('Редактировать')}}</a>
        <button type="button" class="btn btn-primary edit delete mt-2" data-bs-toggle="modal"
                data-bs-target="#exampleModal">
            Удалить
        </button>
    @endcanany
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{__('Подтверждение')}}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p> {{__('Вы уверены что хотите удалить пост?')}} </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{__('Закрыть')}}</button>
                    <form action="{{route('blogs.destroy', ['blog' => $blog->id])}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-secondary" >{{__('Удалить')}}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/confirmation.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ __('Перейдите на свою почту для подтверждения!') }}
                            </div>
                        @endif
                        {{ __('Перейдите на свою почту для подтверждения!') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    {{ __('Вы успешно зарегистрировались!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav me-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ms-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif

                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('personal-page').click();">
                                    {{ __('Личный кабинет') }}
                                </a>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Выйти') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                                <a id="personal-page" href="{{route('users.show', ['user' => Auth::user()->id])}}" class="d-none"></a>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <main class="py-4">
            @if(session('status'))
                <div class="alert alert-primary" role="alert">
                    {{session('status')}}
                </div>
            @endif
            @yield('content')
        </main>
    </div>
</div>
</body>
</html>

resources/views/user/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            {{__('Данные пользователя')}}
        </div>
        <div class="card-body pt-4">
            <blockquote class="blockquote mb-0">
                <footer class="blockquote-footer">Имя: <cite title="Source Title">{{$user->name}}</cite></footer>
                <footer class="blockquote-footer">Почта: <cite title="Source Title">{{$user->email}}</cite></footer>
            </blockquote>
        </div>
    </div>
    @if(count($blogs) != 0)
        <div class="card mt-3">
            <div class="card-header">
                <h3 class="text-center">{{__('Посты пользователя')}}</h3>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 g-4 justify-content-around">
            @foreach($blogs as $blog)
                <div class="col">
                    <div class="card h-100">
                        <div class="card-footer">
                            <small class="text-muted">{{$blog->title}}</small>
                        </div>
                        <a href="{{route('blogs.show', ['blog' => $blog->id])}}" class="card-body text-decoration-none">
                            <h5 class="card-title">{{$blog->title}}</h5>
                            <p class="card-text">{{$blog->body}}</p>
                        </a>
                        <div class="card-footer d-flex flex-column">
                            <small class="text-muted">{{__('Дата:')}} {{$blog->getDateTime()}}</small>
                            <small class="text-muted">{{__('Автор:')}} <a
                                    href="{{route('users.show', ['user' => $blog->user->id])}}">{{$blog->user->name}}</a></small>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endif
    <div class="justify-content-center pb-3 mt-3">
        <ul class="pagination-list">
            {{ $blogs->links() }}
        </ul>
    </div>

@endsection